// backend/middleware/metrics.js
/**
 * Prometheus metrics middleware for Express
 * Collects HTTP request metrics and exposes them
 */

const prometheus = require('prom-client');

// Create metrics
const httpRequestDuration = new prometheus.Histogram({
  name: 'http_request_duration_seconds',
  help: 'Duration of HTTP requests in seconds',
  labelNames: ['method', 'route', 'status'],
  buckets: [0.1, 0.5, 1, 2, 5, 10]
});

const httpRequestTotal = new prometheus.Counter({
  name: 'http_requests_total',
  help: 'Total HTTP requests',
  labelNames: ['method', 'route', 'status']
});

const httpRequestSize = new prometheus.Histogram({
  name: 'http_request_size_bytes',
  help: 'HTTP request size in bytes',
  labelNames: ['method', 'route'],
  buckets: [100, 1000, 10000, 100000, 1000000]
});

const httpResponseSize = new prometheus.Histogram({
  name: 'http_response_size_bytes',
  help: 'HTTP response size in bytes',
  labelNames: ['method', 'route', 'status'],
  buckets: [100, 1000, 10000, 100000, 1000000]
});

const databaseConnections = new prometheus.Gauge({
  name: 'database_connections',
  help: 'Current number of database connections',
  labelNames: ['pool']
});

const databaseQueryDuration = new prometheus.Histogram({
  name: 'database_query_duration_seconds',
  help: 'Duration of database queries',
  labelNames: ['operation'],
  buckets: [0.01, 0.05, 0.1, 0.5, 1, 5]
});

const taskExecutionsTotal = new prometheus.Counter({
  name: 'task_executions_total',
  help: 'Total task executions',
  labelNames: ['status', 'agent_id']
});

const taskExecutionDuration = new prometheus.Histogram({
  name: 'task_execution_duration_seconds',
  help: 'Duration of task executions',
  labelNames: ['agent_id'],
  buckets: [1, 5, 10, 30, 60, 300, 600]
});

const taskQueueDepth = new prometheus.Gauge({
  name: 'task_queue_depth',
  help: 'Number of tasks waiting in queue',
  labelNames: ['queue']
});

const agentUptime = new prometheus.Gauge({
  name: 'agent_uptime_seconds',
  help: 'Agent uptime in seconds',
  labelNames: ['agent_id']
});

const cacheHitRate = new prometheus.Counter({
  name: 'cache_hits_total',
  help: 'Total cache hits',
  labelNames: ['cache_name']
});

const cacheMissRate = new prometheus.Counter({
  name: 'cache_misses_total',
  help: 'Total cache misses',
  labelNames: ['cache_name']
});

const llmInferenceDuration = new prometheus.Histogram({
  name: 'llm_inference_duration_seconds',
  help: 'Duration of LLM inference',
  labelNames: ['model', 'endpoint'],
  buckets: [1, 5, 10, 20, 30, 60, 120]
});

const llmTokensGenerated = new prometheus.Counter({
  name: 'llm_tokens_generated_total',
  help: 'Total tokens generated by LLM',
  labelNames: ['model']
});

const llmErrors = new prometheus.Counter({
  name: 'llm_errors_total',
  help: 'Total LLM errors',
  labelNames: ['model', 'error_type']
});

// Register all metrics
prometheus.register.registerMetric(httpRequestDuration);
prometheus.register.registerMetric(httpRequestTotal);
prometheus.register.registerMetric(httpRequestSize);
prometheus.register.registerMetric(httpResponseSize);
prometheus.register.registerMetric(databaseConnections);
prometheus.register.registerMetric(databaseQueryDuration);
prometheus.register.registerMetric(taskExecutionsTotal);
prometheus.register.registerMetric(taskExecutionDuration);
prometheus.register.registerMetric(taskQueueDepth);
prometheus.register.registerMetric(agentUptime);
prometheus.register.registerMetric(cacheHitRate);
prometheus.register.registerMetric(cacheMissRate);
prometheus.register.registerMetric(llmInferenceDuration);
prometheus.register.registerMetric(llmTokensGenerated);
prometheus.register.registerMetric(llmErrors);

/**
 * Express middleware to collect HTTP metrics
 */
function httpMetricsMiddleware(req, res, next) {
  const start = Date.now();
  const route = req.route?.path || req.path;

  // Record request size
  if (req.get('content-length')) {
    httpRequestSize.observe(
      { method: req.method, route },
      parseInt(req.get('content-length'), 10)
    );
  }

  // Override res.end to capture response metrics
  const originalEnd = res.end;
  res.end = function(chunk, encoding) {
    const duration = (Date.now() - start) / 1000;
    const status = res.statusCode;

    // Record metrics
    httpRequestDuration.observe({
      method: req.method,
      route,
      status
    }, duration);

    httpRequestTotal.inc({
      method: req.method,
      route,
      status
    });

    // Record response size
    if (chunk) {
      const size = Buffer.byteLength(chunk, encoding);
      httpResponseSize.observe({
        method: req.method,
        route,
        status
      }, size);
    }

    // Call original end
    originalEnd.call(res, chunk, encoding);
  };

  next();
}

/**
 * Standalone middleware for Express
 */
function metricsMiddleware(app) {
  // Collect default metrics
  prometheus.collectDefaultMetrics({ timeout: 5000 });

  // HTTP metrics
  app.use(httpMetricsMiddleware);

  // Metrics endpoint
  app.get('/metrics', (req, res) => {
    res.set('Content-Type', prometheus.register.contentType);
    res.end(prometheus.register.metrics());
  });
}

/**
 * Task execution metrics
 */
function recordTaskExecution({
  agentId,
  status, // 'success', 'failure', 'timeout'
  duration,
  queueDepth
}) {
  taskExecutionsTotal.inc({ status, agent_id: agentId });
  taskExecutionDuration.observe({ agent_id: agentId }, duration);
  taskQueueDepth.set({ queue: 'default' }, queueDepth);
}

/**
 * Agent uptime tracking
 */
function updateAgentUptime(agentId, uptimeSeconds) {
  agentUptime.set({ agent_id: agentId }, uptimeSeconds);
}

/**
 * Database metrics
 */
function recordDatabaseMetrics({
  activeConnections,
  operation = 'query',
  duration
}) {
  databaseConnections.set({ pool: 'main' }, activeConnections);
  if (duration) {
    databaseQueryDuration.observe({ operation }, duration);
  }
}

/**
 * Cache metrics
 */
function recordCacheHit(cacheName) {
  cacheHitRate.inc({ cache_name: cacheName });
}

function recordCacheMiss(cacheName) {
  cacheMissRate.inc({ cache_name: cacheName });
}

/**
 * LLM metrics
 */
function recordLLMInference({
  model,
  endpoint = 'completion',
  duration,
  tokensGenerated = 0,
  error = null
}) {
  if (error) {
    llmErrors.inc({ model, error_type: error });
  } else {
    llmInferenceDuration.observe({ model, endpoint }, duration);
    if (tokensGenerated > 0) {
      llmTokensGenerated.inc({ model }, tokensGenerated);
    }
  }
}

module.exports = {
  metricsMiddleware,
  recordTaskExecution,
  updateAgentUptime,
  recordDatabaseMetrics,
  recordCacheHit,
  recordCacheMiss,
  recordLLMInference,
  prometheus,
  // Expose metrics for custom recording
  httpRequestDuration,
  httpRequestTotal,
  httpRequestSize,
  httpResponseSize,
  databaseConnections,
  databaseQueryDuration,
  taskExecutionsTotal,
  taskExecutionDuration,
  taskQueueDepth,
  agentUptime,
  cacheHitRate,
  cacheMissRate,
  llmInferenceDuration,
  llmTokensGenerated,
  llmErrors
};
